app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, BooleanField, SelectField
from wtforms.validators import DataRequired, Length, Email, Regexp
from ..models import Role
from flask_pagedown.fields import PageDownField

class NameForm(FlaskForm):
    name = StringField('What is your name?', validators=[DataRequired()])
    submit = SubmitField('Submit')

class EditProfileForm(FlaskForm):
    name = StringField('Real name', validators=[Length(0,64)])
    location = StringField('Location', validators=[Length(0, 64)])
    about_me = TextAreaField('About me')
    submit = SubmitField('Submit')

class EditProfileAdminForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Length(1,64), Email()])
    username = StringField('Username', validators=[
        DataRequired(), Length(1, 64), Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
                                        'Usernames must have only letters, '
                                        'numbers, dots or underscores')])
    confirmed = BooleanField('Confirmed')
    role = SelectField('Role', coerce=int)
    name = StringField('Real name', validators=[Length(0, 64)])
    location = StringField('Location', validators=[Length(0,64)])
    about_me = TextAreaField('About me')
    submit = SubmitField('Submit')

    def __init__(self, user, *args, **kwargs):
        super(EditProfileAdminForm, self).__init__(*args, **kwargs)
        self.role.choices = [(role.id, role.name)
                            for role in Role.query.order_by(Role.name).all()]
        self.user = user

    def validate_email(self, field):
        if field.data != self.user.email and \
            User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered.')

    def validate_username(self, field):
        if field.data != self.user.username and \
            User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already in user.')

class PostForm(FlaskForm):
    body = PageDownField("waht's on your mind?", validators=[DataRequired()])
    submit = SubmitField('Submit')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from datetime import datetime
from flask import render_template, session, redirect, url_for, flash, request, current_app, make_response
from flask_login import login_required, current_user

from . import main
from .forms import NameForm, EditProfileAdminForm, EditProfileForm, PostForm
from .. import db
from ..models import User, Permission, Post, Role, Follow
from ..decorators import admin_required, permission_required

@main.route('/main/index', methods=['GET', 'POST'])
def index():
    # form = NameForm()
    # if form.validate_on_submit():
    #     return redirect(url_for('/main/index'))
    # return render_template('main/index.html', form=form, name=session.get('name'),
    #                     known=session.get('known', False),
    #                     current_time=datetime.utcnow())
    form = PostForm()
    if current_user.can(Permission.WRITE_ARTICLES) and \
            form.validate_on_submit():
        post = Post(body=form.body.data,
                author=current_user._get_current_object())
        db.session.add(post)
        return redirect(url_for('main.index'))
    # posts = Post.query.order_by(Post.timestamp.desc()).all()
    page = request.args.get('page', 1, type=int)
    show_followed = False
    if current_user.is_authenticated:
        show_followed = bool(request.cookies.get('show_followed', ''))
    if show_followed:
        query = current_user.followed_posts
    else:
        query = Post.query
    pagination = query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out = False
    )
    posts = pagination.items
    return render_template('main/index.html', form=form, posts=posts, Permission=Permission,
                            show_followed=show_followed, pagination=pagination)

@main.route('/main/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    posts = user.posts.order_by(Post.timestamp.desc()).all()
    return render_template('main/user.html', user=user, posts=posts, Permission=Permission)

@main.route('/main/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(user=user)
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user)
        flash('Your profile has been updated')
        return redirect(url_for('.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('main/edit_profile.html', form=form)

@main.route('/main/edit-profile/<int:id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(id):
    user = User.query.get_or_404(id)
    form = EditProfileAdminForm(user = user)
    if form.validate_on_submit():
        user.email = form.email.data
        user.username = form.username.data
        user.confirmed = form.confirmed.data
        user.role = Role.query.get(form.role.data)
        user.name = form.name.data
        user.location = form.location.data
        user.about_me = form.about_me.data
        db.session.add(user)
        flash('The profile has been updated.')
        return redirect(url_for('.user', username=user.username))
    form.email.data = user.email
    form.username.data = user.username
    form.confirmed.data = user.confirmed
    form.role.data = user.role_id
    form.name.data = user.name
    form.location.data = user.location
    form.about_me.data = user.about_me
    return render_template('main/edit_profile.html', form=form, user=user)

@main.route('/post/<int:id>')
def post(id):
    post = Post.query.get_or_404(id)
    return render_template('main/post.html', posts=[post])

@main.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author and \
        not current_user.can(Permission.ADMINISTER):
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.body = form.body.data
        db.session.add(post)
        flash('The post has been updated.')
        return redirect(url_for('main.post', id=post.id))
    form.body.data = post.body
    return render_template('main/edit_post.html', form=form)

@main.route('/follow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('main.index'))
    if current_user.is_following(user):
        flash('You are already following this user.')
        return redirect(url_for('main.user', username=username))
    current_user.follow(user)
    flash('You are now following %s.' % username)
    return redirect(url_for('main.user', username=username))

@main.route('/followers/<username>')
def followers(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid usre.')
        return redirect(url_for('main.index'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followers.paginate(page, per_page=current_app.config['FLASKY_FOLLOWERS_PER_PAGE'],
    error_out=False)
    follows = [{'user': item.follower, 'timestamp': item.timestamp} for item in pagination.items]
    return render_template('main/followers.html', user=user, title="Followers of",
                            endpoint = '.followers', pagination=pagination,
                            follows=follows)

@main.route('/unfollow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('main.index'))
    if not current_user.is_following(user):
        flash('You are not following this user.')
        return redirect(url_for('.user', username=username))
    current_user.unfollow(user)
    flash('You are not following %s anymore.' % username)
    return redirect(url_for('.user', username=username))

@main.route('/followed-by/<username>')
def followed_by(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('main.index'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followed.filter(Follow.followed_id != user.id).paginate(
        page, per_page=current_app.config['FLASKY_FOLLOWERS_PER_PAGE'],
        error_out=False
    )
    follows = [{'user': item.followed, 'timestamp': item.timestamp}
                for item in pagination.items]
    return render_template('main/followers.html', user=user, title="Followed by",
         endpoint='main.followed_by', pagination=pagination, follows=follows)

@main.route('/all')
@login_required
def show_all():
    resp = make_response(redirect(url_for('main.index')))
    resp.set_cookie('show_followed', '', max_age=30*24*60*60)
    return resp

@main.route('/followed')
@login_required
def show_followed():
    resp = make_response(redirect(url_for('main.index')))
    resp.set_cookie('show_followed', '1', max_age=30*24*60*60)
    return resp

app/templates/main/__init__.py
@main.app_context_processor
def inject_permission():
    return dict(Permission=Permission)

app/templates/main/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled" {% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, 
            page = pagination.page-1, **kwargs) }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">
                    {{ p }}
                </a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">
                    {{ p }}
                </a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled">
            <a href="#">&hellip;</a>
        </li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint,
            page = pagination.page + 1, **kwargs) }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/main/_posts.html
<ul class="posts">
    {% for post in posts %}
    <li class="post">
        <div class="post-thumbnail">
            <a href="{{ url_for('main.user', username=post.author.username) }}">
                <img class="img-rounded profile-thumbnail" src="{{ post.author.gravatar(size=40) }}">
            </a>
        </div>
        <div class="post-content">
            <div class="post-data">
                {{ moment(post.timestamp).fromNow() }}
            </div>
            <div class="post-author">
                <a href="{{ url_for('main.user', username=post.author.usrename) }}">
                    {{ post.author.username }}
                </a>
            </div>
            <div class="post-body">
                {% if post.body_html %}
                    {{ post.body_html | safe }}
                {% else %}
                    {{ post.body }}
                {% endif %}
            </div>
            <div class="post-footer">
                {% if current_user == post.author %}
                <a href="{{ url_for('main.edit', id=post.id) }}">
                    <span class="label label-primary">Edit</span>
                </a>
                {% elif current_user.is_administrator() %}
                <a href="{{ url_for('main.edit', id=post.id) }}">
                    <span class="label label-danger">Edit [Admin]</span>
                </a>
                {% endif %}
                <a href="{{ url_for('main.post', id=post.id) }}">
                    <span class="label label-default">Permalink</sapn>
                </a>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/main/edit_post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
    Flasky - Edit Post
{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Post</h1>
</div>
<div>
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/main/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - Edit Profile{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Yout Profile</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/main/followers.html
{% extends "base.html" %}
{% import "main/_macros.html" as macros %}

{% block title %}Flasky - {{ title }} {{ user.username }}{% endblock %}
{% block page_content %}
<div class="page-header">
    <h1>{{ title }} {{ user.username}} </h1>
</div>
<table class="table table-hover followers">
    <thead>
        <tr>
            <th>User</th>
            <th>Since</th>
        </tr>
    </thead>
    {% for follow in follows %}
    <tr>
        <td>
            <a href="{{ url_for('.user', username=follow.user.username) }}">
                <img class="img-rounded" src="{{ follow.user.gravatar(size=32) }}">
                {{ follow.user.usrename }}
            </a>
        </td>
        <td>
            {{ moment(follow.timestamp).format('L') }}
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}
{% import "main/_macros.html" as macros %}

{% block title %}Flasky{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Hello, {% if current_user.is_authenticated %}
        {{ current_user.username }}
        {% else %}Stranger{% endif %}!</h1>
</div>
<div>
    {% if current_user.can(Permission.WRITE_ARTICLES) %}
    {{ wtf.quick_form(form)}}
    {% endif %}
</div>
<div class="post-tabs">
    <ul class="nav nav-tabs">
        <li{% if not show_followed %} class="active"{% endif %}>
            <a href="{{ url_for('main.show_all') }}">All</a>
        </li>
        {% if current_user.is_authenticated %}
        <li{% if show_followed %} class="active"{% endif %}>
            <a href="{{ url_for('main.show_followed') }}">Followers</a>
        </li>
        {% endif %}
    </ul>
    {% include 'main/_posts.html' %}
</div>
<!-- <ul class="posts">
    {% for post in posts %}
    <li class="post">
        <div class="post-thumbnail">
            <a href="{{ url_for('.user', username=post.author) }}">
                <img class="img-rounded profile-thumbnail" src="{{ post.author.gravatar(size=40) }}">
            </a>
        </div>
        <div class="post-content">
            <div class="post-data">{{ moment(post.timestamp).fromNow() }}</div>
            <div class="post-author"><a href="{{ url_for('.user', username=post.author.username) }}">
                {{ post.author.username }}
            </a></div>
            <div class="post-body">{{ post.body }}</div>
        </div>
    </li>
    {% endfor %}
</ul> -->
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, 'main.index') }}
</div>
{% endif %}
<!-- <div class="page_content">
    <h1>Hello, {% if current_user.is_authenticated %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h1>
    {% if not known %}
    <p>Pleased to meet you!</p>
    {% else %}
    <p>Happy to see you again</p>
    {% endif %}
</div>
{{ wtf.quick_form(form) }} -->
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/main/post.html
{% extends "base.html" %}

{% block title %}Flasky - Post{% endblock %}

{% block page_content %}
{% include 'main/_posts.html' %}
{% endblock %}

app/templates/main/user.html
{% extends "base.html" %}

{% block title %}Flasky{% endblock %}

{% block page_content %}
<!-- <div class="page-header">
	<h1>Hello, {{ name }}!</h1>
</div> -->
<div class="page-header">
	<img calss="img-rounded profile-thumbnail" src="{{ user.gravatar(size=256) }}">
	<h1>{{ user.username }}</h1>
	{% if user.name or user.location %}
	<p>
		{% if user.name %}{{ user.name }}{% endif %}
		{% if user.location %}
			From <a href="http://maps.google.com/?q={{ user.location }}">
				{{ user.location }}
			</a>
		{% endif %}
	</p>
	{% endif %}
	{% if current_user.is_administrator() %}
	<p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
	{% endif %}
	{% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
	<p>
		Member since {{ moment(user.member_since).format('L') }}.
		Last seen {{ moment(user.last_seen).fromNow() }}.
	</p>
	<p>{{ user.posts.count() }} blog posts.</p>
	<p>
		{% if current_user.can(Permission.FOLLOW) and user != current_user %}
		{% if not current_user.is_following(user) %}
		<a href="{{ url_for('main.follow', username=user.username) }}" class="btn btn-primary">
			Follow
		</a>
		{% else %}
		<a href="{{ url_for('main.unfollow', username=user.username) }}" class="btn btn-default">
			Unfollow
		</a>
		{% endif %}
		{% endif %}
		<a href="{{ url_for('main.followers', username=user.username) }}">
			Following: <span class="badge">{{ user.followers.count() - 1}}</span>
		</a>
		<a href="{{ url_for('main.followed_by', username=user.username) }}">
			Followed: <span class="badge">{{ user.followed.count() - 1}}</span>
		</a>
		{% if current_user.id_authenticated and user != current_user and user.is_following(current_usre) %}
			<span class="label label-default">Follows you</span>
		{% endif %}
	</p>
	<p>
		{% if user == current_user %}
		<a class="btn btn-default" href="{{ url_for('.edit_profile') }}">
			Edit Profile
		</a>
		{% endif %}
	</p>
	<p>
		{% if current_user.is_administrator() %}
		<a class="btn btn-danger"
			href="{{ url_for('main.edit_profile_admin', id=user.id) }}">
			Edit Profile [Admin]
		</a>
		{% endif %}
	</p>
</div>
<h3>Posts by {{ user.usrename }}</h3>
{% include 'main/_posts.html' %}
{% if pagination %}
<div class="pagination">
	{{ macros.pagination_widget(pagination, 'main.user', username=user.username) }}
</div>
{% endif %}
{% endblock %}